# Generated by Django 5.1.2 on 2025-02-20 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbItem_Cesta',
            fields=[
                ('ID_Item_Cesta', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=255)),
                ('Quant_padrao', models.PositiveIntegerField()),
                ('Quant_Obtida', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TbAsItem_Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantidade', models.PositiveIntegerField()),
                ('ID_Item_Cesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciador.tbitem_cesta')),
            ],
        ),
        migrations.CreateModel(
            name='TbModelo_Cesta',
            fields=[
                ('id_Cesta', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('Quant_Arrecadadas', models.PositiveIntegerField()),
                ('Quant_doadas', models.PositiveIntegerField()),
                ('Item_e_cesta', models.ManyToManyField(through='gerenciador.TbAsItem_Modelo', to='gerenciador.tbitem_cesta')),
            ],
        ),
        migrations.CreateModel(
            name='TbCampanhas',
            fields=[
                ('ID_Campanha', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=255)),
                ('Prazo', models.DateField()),
                ('Quantidade_Cestas', models.PositiveIntegerField()),
                ('Id_Cesta', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gerenciador.tbmodelo_cesta', verbose_name='Modelo_cesta')),
            ],
        ),
        migrations.AddField(
            model_name='tbasitem_modelo',
            name='id_Cesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciador.tbmodelo_cesta'),
        ),
    ]
