# Generated by Django 5.1.2 on 2025-02-20 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbasitem_modelo',
            name='Quantidade',
        ),
    ]
