# Generated by Django 5.1.2 on 2025-02-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0002_remove_tbasitem_modelo_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbcampanhas',
            name='status',
            field=models.CharField(choices=[('em andamento', 'Em andamento'), ('concluida', 'Concluída'), ('atrasada', 'Atrasada'), ('concluida com atraso', 'Concluída com atraso')], default='em andamento', max_length=20),
        ),
    ]
