# Generated by Django 5.1.2 on 2025-02-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0003_tbcampanhas_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbitem_cesta',
            name='Quant_Obtida',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tbitem_cesta',
            name='Quant_padrao',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
