# Generated by Django 5.1.2 on 2025-02-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0004_alter_tbitem_cesta_quant_obtida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbitem_cesta',
            name='Quant_padrao',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tbmodelo_cesta',
            name='Quant_Arrecadadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tbmodelo_cesta',
            name='Quant_doadas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
