# Generated by Django 5.1.2 on 2025-02-23 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0005_alter_tbitem_cesta_quant_padrao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcampanhas',
            name='Id_Cesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciador.tbmodelo_cesta', verbose_name='Modelo_cesta'),
        ),
    ]
