# Generated by Django 5.1.2 on 2025-07-25 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0006_alter_tbcampanhas_id_cesta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TbDonation',
            fields=[
                ('id_Donation', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.PositiveIntegerField()),
                ('Validade', models.DateField()),
                ('confirmado', models.BooleanField(default=False)),
                ('id_Item_Cesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciador.tbitem_cesta', verbose_name='Item')),
                ('id_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
